DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS mcqchoice;
CREATE TABLE question(QUESTION_ID INT PRIMARY KEY, QUESTION_TITLE VARCHAR(255), TOPIC VARCHAR(255), DIFFICULTY INT);
CREATE TABLE mcqchoice(MCQCHOICE_ID INT PRIMARY KEY, CHOICE VARCHAR(255), VALID BOOLEAN,
						QUESTION_ID INT, FOREIGN KEY (QUESTION_ID) REFERENCES question);
